source "https://rubygems.org"

gem "rspec"
gem "activerecord"
gem "sqlite3"
gem "rake"
gem "database_cleaner"
gem "pry"
gem "hoe"
gem "hoe-bundler"
gem "hoe-gemspec"
gem "mini_portile"
gem "minitest"
gem "rake-compiler"
gem "rake-compiler-dock"
gem "rdoc"
